import { getUserInfoData } from "../../info-service/user-info.js";
import { isAdmin } from "../../../index.js";
import { getGlobalPrefix } from "../../service.js";
import { removeMention } from "../../../utils/format-util.js";

const scoldUsers = new Map();
let isScoldingActive = false;

export async function scoldUser(api, message) {
  const prefix = getGlobalPrefix();
  const senderId = message.data.uidFrom;
  const threadId = message.threadId;
  const content = removeMention(message);

  if (content.toLowerCase() === `${prefix}scold tha`) {
    if (isAdmin(senderId, threadId) && isScoldingActive) {
      isScoldingActive = false;
      api.sendMessage({ msg: "Dạ Đại Ca em sẽ tha cho nó.", quote: message }, threadId, message.type);
      return;
    }
  }

  let delay = 5001;
  const args = content.split(' ').filter(arg => arg !== '');
  const delayArg = args.find(arg => {
    const cleanArg = arg.toLowerCase().replace('ms', '');
    return !isNaN(cleanArg);
  });

  if (delayArg) {
    const cleanDelay = parseInt(delayArg.toLowerCase().replace('ms', ''));
    delay = cleanDelay;
    if (delay < 100) delay = 100;
    delay = Math.min(delay, 10000);
  }

  if (!isScoldingActive) {
    isScoldingActive = true;
  }

  if (!message.data.mentions || message.data.mentions.length === 0) {
    await api.sendMessage({ msg: ":D Đại Ca muốn em chửi ai? 🚀", quote: message }, threadId, message.type);
    return;
  }

  const userId = message.data.mentions[0].uid;

  if (isAdmin(userId, threadId)) {
    await api.sendMessage(
      { msg: "Không thể ra lệnh chửi quản trị bot. 🚫", quote: message },
      threadId,
      message.type
    );
    return;
  }

  if (scoldUsers.has(userId)) {
    await api.sendMessage(
      {
        msg: "Người này đang bị chửi.",
        quote: message,
      },
      threadId,
      message.type
    );
    return;
  }

  const scoldMessages = [
    "Bạn ra đây tao bảo, hiện hồn nhanh con chó",
    "Hiện hồn nhanh Không tao đốt nhà Bạn giờ",
    "Địt mẹ Bạn bố nói tử tế mà Không dậy à",
    "Nhanh ra chửi nhau với tao",
    "Tao ném trứng thối đổ dầu đổ xăng vào nhà Bạn giờ",
    "Hoá ra cũng chỉ là con chó mang hình dáng người",
    "Làm người thì khó, làm chó thì dễ ..!!",
    "Đừng tỏ vẻ máu liều nhiều hơn máu não",
    "Đụ con đĩ mẹ Bạn",
    "Con chó Bạn đứng lên đi",
    "Địt mẹ bố gọi Không nghe à",
    "Hiện hồn đi thằng mặt lồn",
    "Đĩ mẹ Bạn ra đây bô xem nào",
    "Tao ném trứng thối đổ dầu đổ xăng vào nhà Bạn giờ",
    "Bố Bạn bắn rap chết cụ Bạn giờ",
    "Vậy thì xin mời nghe tao rap địt chết cả lò Bạn nhà con",
    "Đầu tiên tao xin phép địt từ trên xuống dưới con",
    "Tao địt từ lỗ lồn đến lỗ nhị con lồn",
    "Lồn thì to như lồn trâu thủ dâm ống cống ấy nhé con",
    "Tao địt chắc 2 thằng như tao chưa đủ lấp cái lỗ lồn nhà Bạn đâu",
    "Đụ con đĩ mẹ Bạn",
    "Thằng óc cức",
    "Mẹ m đẻ m ra đau lồn chứ được con cặc gì",
    "Con mẹ Bạn đẻ m ra đau lồn chứ được con cặc gì",
    "...",
    "lồn mẹ mày ăn hại=))",
    "cn đĩ ngu ei=))",
    "mày óc chó rõ mà=)))",
    "cn đỉ mồ cồi cay ah r phải hơm",
    "ớt ah rõ nun mà",
    "ai cho mày slow v á",
    "cn ngu 0 cha 0 mẹ lên mxh đú ak=)))",
    "cha mẹ m bị ah đập tơi bời mà",
    "cn gái mẹ m bị ah dẫm đạp mà=)))",
    "cn mụ già đó bị ah sút tung lồn tử vong nun mà ccho ngu bại não=)))",
    "tk đĩ cha mày nó óc chó quá bị ah đập ngay trc mắt m mà=))))",
    "m bất lực khóc khi thấy ah đập cn đỉ cha m mà",
    "tao đụ rách lồn cn đỉ mẹ mày nun mà=))))",
    "cn mẹ m là đỉ đứng đường bị mấy ccho hiếp dâm liên tục 7749 ngày lun mà=)))",
    "cô đĩ bất lực r phải hơm=)))",
    "mày lmj đc ah nè ccho ngu ei=))))",
    "m mếu r phải hơm cn chó ngu ei=))",
    "đéo mẹ mày tếu à=))))",
    "cn chó nghịch tử tự tay giết chính cn đỉ mẹ nó vì k đc cn gái mẹ nó đy cho đụ=))))))",
    "mày hận ah r đúng k cn đỉ ngu=))) =))) =)))",
    "t sỉ nhục cn mẹ mày cơ=)))",
    "tk cha mày bị ah tra tấn 3 ngày 3 đêm nun mà=))",
    "cn đỉ nó cay cay ah r kìa=))))",
    "ah cho phép m khóc chx đó=)))",
    "t cho m mếu à=)) =)))",
    "cái sự cay cú của m đạt x1000 r phải hơm=)))",
    "cn đĩ slow ác v =)))",
    "m cay ah rõ nun mà kkk=))",
    "óc chó sồn mau đê em ei=))))",
    "mày hăng lên ah xem đê=))",
    "lên ẳng ẳng như cách m ảo ửa đê=)) =)))",
    "cái cn đỉ mẹ mày bất lực r è=))",
    "cay ah mà đâu có lmj đc ah",
    "cn đỉ mồ côi mất cha vì bị ah giết cha",
    "mất mẹ vì cn gái mẹ nó bỏ nó theo ah xg bị ah tra tấn",
    "cn gái mẹ ngoài rộng mà còn thâm nx=)))",
    "tk cha m lm quần quật để cn chó như m lên mxh đú ửa =)))",
    "cn chó cay đập điện thoại xg bị ôg già đánh=)))",
    "sau khi bị đánh cay rút dao tự tay giết cha nó=))",
    "cn chó ngu sau khi bị ah chửi nó kiểu",
    "cn đỉ ei m lên sủa lofi ah xem đê",
    "ai cho m ngồi trg góc tối khóc mà k care ah=))",
    "cn đỉ mếu khóc vì k đc đụ gái mẹ nó=)))",
    "miệng thì chối nhưng não thì nghĩ cách loạn luân =)))",
    "nhìn cu e bất lực mà ah mắc cười",
    "mấy cái ngôn lỏ của m đủ lm ah cay ak",
    "cố làm bố hận m đê",
    "lm ah ớt m đi ccho ngu ei",
    "nghĩ bố cay m ak=)))",
    "não thì tự nhận mik win nhưng thực tế là bại t mà=))",
    "nó cay cay tui r kìa",
    "cn đĩ bại não cố tí ah xem",
    "cn chó vô dụng phế nhất mxh mang tên m mak",
    "đỉ ngu cố gắng win nhưng đâu có đc",
    "cố tí đi sắp thua t r kìa",
    "lose cố gắng tí đê",
    "0 trình đòi pem ai=))",
    "lm trò hề cho thiên hạ xem ak=)))",
    "cn đĩ ngu lên đê=))",
    "ah cho phép m câm ak",
    "ai cho m nín họng chó v",
    "nhìn ah gõ m mà học hỏi",
    "cố gắng học lỏm ah để mai sau cầm ngôn ah pem ah",
    "hôm nay m gặp ah là chết cái cn gái mẹ m r =)))",
    "ah cầm cái bồ cào cái nát cái lồn mẹ mày mà=))",
    "thấy ah chửi m chỉ bt câm nín thôi ak=))",
    "chả lmj đc ah ak=}}",
    "ah khuyên tht m nên chết đi=))",
    "sống làm cái đéo giề =))",
    "cn đỉ mẹ mày nun=))",
    "m có căn để pem ah hơm=))",
    "cái lồn mẹ mày nun nè=))",
    "cái cn chó ngu eiiii=)))",
    "ah cho m sủa sao m ko sủa đê",
    "nãy hăng lắm mà=}}",
    "cn đỉ ăn bánh mì quanh năm suốt tháng",
    "ăn lun cả tinh trùng của cn đỉ cha nó",
    "cn đỉ lgbt bày bình chơi ah mà ai ngờ lép vế",
    "cn mẹ mày là đĩ cơ=)))",
    "m phế đến nổi chửi 1 đứa k bt ửa r noti ngầu ngầu=)))",
    "hôm nay gặp ah bại trận trc ah lun mà=)))",
    "cn chó oanh liệt lắm h sao im thin thít r nè",
    "cái tk đĩ ăn hại=)))",
    "ah cầm đinh ba xiên chết cha m cơ=))",
    "ah đụ rách lồn mẹ mày mà",
    "m rung sợ cha rõ mà",
    "ah sút tung lồn mẹ m =))",
    "ah treo cổ cha mày mà",
    "cn đĩ ngu lại bố ko v =))",
    "nhìn m đuối đuối r kìa cn ngu =))",
    "phèn lồn mà tưởng mình bá hả =))",
    "làm đc bố thua m ko v cn đĩ =))",
    "mày xàm xàm jv cn đĩ =))",
    "cái con đĩ mẹ mày ngôn phèn lồn mà m tưởng dame cao hả con đĩ =))",
    "cái lồn mẹ mày làm lại tao v cn chó đú =))",
    "ngày m gặp anh là ngày ah đập chết cn gái mẹ mày ấy =))",
    "cái tk lồn mặt cặc sida mà tưởng mình hay =))",
    "m câm 1 cái là ah triệu hồi thiên lôi đánh chết cn đĩ mẹ mày ấy =))",
    "ah cho m sủa lofi trog 5p đấy cn đĩ ơi =))",
    "ngôn lồn phèn mà tưởng ngầu =))",
    "m tưởng m hw hả cn đĩ lồn ơi =))",
    "trình m đáy xã hội còn t trên đọt cây cn đĩ mẹ mày r =))",
    "ngu lồn sĩ sĩ t đánh chết cn mẹ mày =))",
    "cn lồn mếu r hả e ơi =))",
    "t ước cay đc bởi cái ngôn lồn óc cặc sida đần độn phèn lồn của m ấy =))",
    "m cố làm ah cay đi cn đĩ ơi =))",
    "cái cn lồn yếu đuối mà sĩ à e =))",
    "đụ đĩ mẹ mày phế vật à e =))",
    "t cầm đinh ba xiên chết cha m mà =))",
    "t đụ rách cái lồn mẹ mày mà =))",
    "bố réo tổ tông nhà m còn đc =))",
    "cn chó loạn luân vs cn gái mẹ nó rõ mà=))",
    "t tung skill lm cn gái mẹ m die lun cơ =))",
    "tk đĩ culi ăn hại chửi k sát thương mà =))",
    "m muốn win cha m đâu có đc =))",
    "cn đĩ mẹ mày làm lại ah ko tk ăn hại =))",
    "cn chó âm binh đầu đinh =))",
    "cn chó 0 cha 0 mẹ oai ak=))",
    "văn thơ ah bay trog gió dã vô lồn mẹ mày =))",
    "đĩ ngu idea hạn hẹp =))",
    "cái lồn mẹ mày bị ah đụ nát mà cn đĩ lồn =))",
    "yếu mà sĩ sĩ à e =))",
    "m cố trụ vs ah nha cn đĩ ơi =))",
    "m mà rớt là cn mẹ mày chết =))",
    "m cố gắng nha cn chó mặt cặc =))",
    "rớt ah 1 cái là đụ má cn đĩ mẹ mày die liền á =))",
    "t cầm ak47 sấy nát cái gia đình lồn ăn hại của m =))",
    "tk lồn ơi m lên sĩ lẹ cho anh =))",
    "m sợ bố phải ko cn chó =))",
    "ngữ m vạn kiếp vẫn chưa win đc ah cơ =))",
    "cn chó ăn hại tự xưng hw bị ah đánh chết mẹ cơ =))",
    "m làm thân vs t là t vã nát lồn má mày =))",
    "m phản kháng trg vô vọng à =)))",
    "t đá chết cha m mà =))",
    "t thay trời tiêu diệt cn má m =)))",
    "t chửi cha mắng mẹ m mà =))",
    "cn chó ngu cay ah=))",
    "cn đĩ ngu ăn hại=))",
    "m muốn win cha m đâu có đc =))",
    "noti đc cha khó như lên trời ngược lại noti m ez vc =))",
    "cái cn đĩ ngu ngu bắt đầu bí bí r kìa =))",
    "cn đĩ chị m mà cn lồn ơi =))",
    "lồn mẹ mày ăn hại mà đú ửa hả =))",
    "cố gắng tí nha cn đĩ lồn =))",
    "đĩ mẹ mày bày đặt sĩ sĩ hả cn ngu =))",
    "lồn má mày cấm out box nghe chưa cn ăn hại =))",
    "1 khi ah réo là ah réo chết cn mẹ mày thì thôi mà =))",
    "đừng có quỳ xuống cầu xin ah nghe chx =))",
    "ăn hại mà tưởng mình là hw cơ =))",
    "lại phải win cn chó như m =))",
    "chuỗi 1 triệu tiêu diệt cn gái mẹ mày =))",
    "cn lồn nghịch tử tự tay giết cha đánh đuổi mẹ ruột mà chối =))",
    "cn đĩ xạo lồn mà oai =))",
    "cn đĩ mẹ mày xạo lồn hả cn chó =))",
    "cn gái mẹ mày làm lại tao ko v cn đĩ mặt cặc ăn hại =))",
    "đụ đĩ mẹ mày đuối rõ mà e =))",
    "chối cái ah vã cn gái mẹ mày chết =))",
    "lồn ăn hại ơi =))",
    "cn đĩ mẹ mày bị ah réo chết mẹ mà cn đĩ =))",
    "bị ah trụ cho rớt trg bất lực nên cay pk =))",
    "hận bố r phải k cn đĩ ăn hại =))",
    "ngôn ah dame cao chứ ai như cn đĩ ngôn phèn như m v =))",
    "m đừng để ah noti m ez v chứ =))",
    "cái cn đĩ ăn hại lên mxh sĩ =))",
    "đụ cn gái mẹ mày sao đó =))",
    "cái lồn cn gái mẹ mày cay t hả =))",
    "cn gái mẹ mày đứng đường nuôi m ăn học mà =))",
    "cn mẹ mày chết kìa =))",
    "t giết cn gái mẹ mày r vứt xuống sông hồng =))",
    "cn đĩ ngu ngu cay t r à =))",
    "cn lồn sồn như ban đầu cho bố đi ơ =))",
    "cn đĩ mẹ mày =))",
    "phế vật hả cn chó ơi =))",
    "lm bố thua m mau đi cn chó mặt cặc ăn hại =))",
    "cn chó loạn luân vs cn gái mẹ nó rõ mà=))",
    "t sút chết bà già m mà=))",
    "m mồ côi hả cn đĩ mặt cặc =))",
    "đụ đĩ mẹ mày phế kinh à =))",
    "cn lồn ơi lên sĩ tiếp cho ah =))",
    "sồn như ban đầu cho bố đi ơ =))",
    "cn đĩ mẹ mày cay t à =))",
    "đụ cn gái mẹ mày sắp thua bố hả cn đĩ lồn =))",
    "cn gái má mày bị ah đụ nát cái lồn =))",
    "cn đĩ cấm thua t nghe chưa =))",
    "lm đc t thua m ko v e =))",
    "cái cn miên ơi sĩ tiếp cho t =))",
    "m sồn như ban đầu cho t lẹ e =))",
    "cái cn đĩ mẹ mày phế vật à e =))",
    "cn lồn ngu ăn hại ơi =))",
    "đụ đĩ mẹ mày bị giết mà =))",
    "cn đĩ mặt cặc sồn mau cho ah đi cn đĩ ăn hại ơi =))",
    "đụ má mày sĩ sĩ ngu à e =))",
    "sĩ trai hay sĩ gái v mà nhìn đần v e =))",
    "cái cn lồn mồ côi mà giấu t hả =))",
    "đụ má mày mồ cồi mà xạo lồn =))",
    "lồn mẹ mày cn chó ơi hăng mau k =))",
    "đéo cho m chậm nghe chưa =))",
    "sồn lồn mẹ mày lên ah xem đê =))",
    "cn đĩ mặt cặc cay cay t r =))",
    "đụ đĩ mẹ mày tức bố hả =))",
    "cn mặt lồn ăn hại mà còn xạo lồn =))",
    "ngữ lồn m khi nào lm đc t cay v e =))",
    "cn đĩ đầu trâu mặt ngựa tức t r hả =))",
    "cái lồn má mày nhà nghèo xây mộ mẹ m bé v =))",
    "cái cn đĩ bán dâm mang tên cn gái mẹ mày =))",
    "mẹ mày chết ơ =))",
    "cn đĩ mua thuốc giảm cân đi =))",
    "m loạn luân vs mẹ mày mà =))",
    "t chửi cha mắng cái cn gái mẹ mày =))",
    "cái lồn mẹ mày sợ t à =))",
    "cn lồn ơi m bảo t bot tool này nọ là t chửi chết mẹ mày =))",
    "cái con lồn ngu thấy ah tốc độ quá à =))",
    "cái cn đĩ mẹ mày chết =))",
    "cn chó ngu lồn =))",
    "mẹ mày cn chó =))",
    "sợ bố r à cn ngu =))",
    "đĩ mẹ mày ơ =))",
    "cn gái mẹ mày nun =))",
    "cn đĩ mập địch =))",
    "lm lại ah k v =))",
    "cn đĩ ngu ăn hại =))",
    "đụ đĩ mẹ mày tức t à =))",
    "cái cn lồn ơi =))",
    "cn đĩ mẹ mày m ơ =))",
    "t sút tung lồn mẹ mày cơ =))",
    "cn choa ei=))=))=))=))",
    "123=))=))=))=))",
    "m chay anh cmnr=))=))=))=))=))",
    "m yeu ot z tk nfu=))=))=))=))=))",
    "m cham vl e=))=))=))",
    "slow lun e=))=))=))=))",
    "yeu z cn dix=))=))=))=))",
    "tk 3de=))=))=))=))=))",
    "tk dix lgbt=))=))=))=))",
    "cn choa nfu=))=))=))=))=))",
    "deo co canh lun e=))=))=))=))",
    "m cham vl e=))=))=))=))",
    "m yeu v=))=))=))=))=))=))",
    "yeu ro=))=))=))=))=))=))",
    "bia a=))=))=))=))",
    "tk dix=))=))=))=))",
    "mau k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "cham a=))=))=))=))=))=))",
    "tk nfu =))=))=))=))=))",
    "mau ti de=))=))=))=))",
    "yeu ot vcl=))=))=))=))",
    "cmm dot tu kia=))=))=))",
    "lien tuc de=))=))=))=))=))",
    "alo may cn cho nu=)) =)) =))",
    "cmm =))=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk nfu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "alo alo=))=))=))=))",
    "cn tÃ³ ei=))=))=))",
    "mau ti e=))=))=))=))",
    "mau de=))=))=))=))",
    "yeu ot v=))=))=))",
    "tk ccho ei=))=))=))",
    "m tru noi k ay=))=))=))=))",
    "tk 3de=))=))=))=))",
    "cn ga ei=))=))=))=))",
    "m ga vl lun e=))=))=))=))",
    "alo alo=))=))=))",
    "sao ay nhi=))=))=))=))",
    "anh lai win a=))=))=))=))",
    "uoc loser ma=))=))=))=))",
    "tk nfu ei=))=))=))=))",
    "slow k ay=))=))=))",
    "cn cho =))=))=))",
    "speed lun e=))=))=))",
    "toi die k e=))=))=))",
    "mau me m di=))=))=))=))",
    "tk cho nfu=))=))=))=))=))",
    "m ot bo ro=))=))=))=))",
    "m bia a=))=))=))=))=))",
    "con gi khac k=))=))=))=))",
    "tk ga ei=))=))=))",
    "mau k e=))=))=))=))=))",
    "anh win cmnr=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk nfu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau me m di=))=))=))=))",
    "tk cho nfu=))=))=))=))=))",
    "a Ä‘áº¥ng hot war mà=))=))=))=))",
    "cmm chối à=))=))=))=))",
    "a hw mẹ r=))=))=))=))",
    "con gi dau ma noi =))=))=))=))",
    "a treo co me m ma=))=))=))=))",
    "a win ma=))=))=))=))",
    "m bia a=))=))=))=))",
    "tk nfu ri=))=))=))=))=))",
    "m ngu v =))=))=))=))",
    "ngu ro lun e=))=))=))=))=))",
    "bia a e=))=))=))=))",
    "le de alo =))=))=))=))=))",
    "s do =))=))=))=))=))",
    "m sao =))=))=))=))",
    "m chạy a mà=))=))=))=))",
    "m bịa à=))=))=))=))",
    "tk nu=))=))=))=))=))",
    "cmm =))=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk nfu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "alo alo=))=))=))=))",
    "nó cay t vcl ra r ae=)))",
    "đĩ mẹ nó nữa chứ=)))",
    "s đó tk cẩu ưi=)))",
    "t chat dài như năm tháng cha nó ở tù=)))",
    "đúng tk ngoại tộc=)))",
    "đĩ má nó=)))",
    "sua nhanh memay ko tk ngu=))=))=))",
    "chui bo lien tuc k tk e=))=))",
    "me may siu oc cho dk e=))=))=))",
    "tk lon siu vo dung an cut e=))=))=))",
    "keo treo zalo 10box 10m ko e=))=))",
    "lien tuc 24 vs anh dc k=))=))",
    "siu met moi r dk tk cuk ngu e=))=))=))",
    "tk lon cho siu run ray r dk e=))=))=))",
    "lam anh cay dc ko tk ngu=))=))=))",
    "con bím ngu siu tuc r a=))=))",
    "tk loz silicon chat vs ah dc k=))=))=))",
    "chui bo nhanh nhen ti dei=))=))",
    "keo tien vs bo ti k=))=))",
    "toxic lau dai ti ko tk cuk=))=))",
    "me may siu vo dung r dk e=))=))=))",
    "tk lon ngu loser bo r dk em=))=))=))",
    "tk loz mat me siu cay a=))=))",
    "uc che bo x100 r dk e=))=))=))",
    "chui nhau hang hai ti ko=))=))=))=))",
    "kho khan khi gap anh dung k tk ngu=))=))=))",
    "con me may an hai dk em ei=))=))",
    "me may chet vi benh tat dk=))=))=))",
    "tk loz cuk culi cay bo k=))=))=))",
    "am uc bo lam r dk=))=))",
    "siu cay anh ma dk e=))=))",
    "chui dc anh ko e=))=))=))=))",
    "tk loz cuk cho memay ei=))=))",
    "tk cuk cho siu ngu ei=))=))=))",
    "memay loser bo r dk=))=))=))",
    "chui bo lien tuc dc k ay=))=))",
    "nhanh nhen ti ko e=))=))=))",
    "siu met moi r dk tk ngu=))=))=))",
    "tk cuk loz ngu e=))=))=))",
    "hang hai vs bo ti ko=))=))=))",
    "chat 24h vs anh dc k=))=))",
    "memay len gg search cach wjn a dk=))=))=))",
    "bo may siu manh dk=))=))",
    "hoa khi bash anh ti k=))=))=))",
    "tk bim siu uc che=))=))=))",
    "lam v co giup memay song lai k=))=))",
    "tk loz ngheo nan ei=))=))=))",
    "memay nha la dk tk e=))=))=))",
    "tk nha ngheo cay bo k=))=))=))",
    "chui bo nhanh dc k=))=))",
    "tk loz ngu bi bo chui dk=))=))",
    "siu cay cu bo dk tk e=))=))",
    "tk cha k chet r dk e=))=))",
    "tk cuk cho dit me may=))=))=))",
    "bo may siu manh dk=))=))=))",
    "chat lien tuc 24h vs anh ko=))=))=))",
    "tk cho siu vo dung ei=))=))=))",
    "bo bash chet may dk e=))=))=))",
    "tk loz siu ga chui dc a ko=))=))=))",
    "tk cho bi a chui sml a em=))=))=))",
    "con me may siu uc che r dk e=))=))=))",
    "chui bo lien tuc 1ti nam ko=))=))=))",
    "lam keo 100m vs anh k=))=))=))",
    "chui a nhanh ti ko=))=))=))",
    "tk loz siu an hai dk e=))=))",
    "keo treo zalo 10box vs ah ko=))=))",
    "tk loz indo siu cay",
    "tuc gian lam r dk thang e=))=))=))",
    "chui win bo dc k e=))=))",
    "co gang win a dei=))=))=))",
    "co chui hang dei em=))=))🎮",
    "bo may siu manh dk tk e",
    "tk cac bi bo chui cay k",
    "con me may loser bo dk e",
    "bo manh siu manh dk e",
    "bo may super vippro dk e",
    "tk cho siu ot bo dk=))",
    "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))",
    "con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))",
    "làm màu mà bị tao chửi rung cái con cặc:)))",
    "thằng bê đê ảo cặc đòi cân và cái kết:)))",
    "con đĩ mẹ của mày thèm cứt tao dữ lắm:)))",
    "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))",
    "ai cho mày sủa tao cho mày sủa chưa?",
    "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á",
    "mẹ đĩ của m dắt m vào sàn à=))",
    "mẹ mày bú cặc t để m được vào sàn mà",
    "đập đá hít cần sa nhiều xong sủa bậy à",
    "mẹ mày bị tao dã vào lồn=)))",
    "địt mẹ mày sướng tê con cặc=)))",
    "mẹ mày bị tao địt rên ư ử=)))",
    "tao địt mẹ mày nát lồn mà=)))",
    "mẹ mày bị tao cưỡng hiếp=)))",
    "sao mày lề mề dị con",
    "mày bệnh nặng lắm à:)))",
    "ko cảm hứng để hăng à :)))",
    "nghèo k có nghi lực à:))",
    "m thèm cứt t mà:))",
    "chối t giết cha má m nè:)))",
    "k lên t tuyệt chủng m nhen cn thú",
    "mày ngưng là con đĩ mẹ mày chết?",
    "Cha mày đụ chó sinh ra mày đk dog :)))",
    "bị tao chọc cay hơn con chó luôn=)))",
    "Mẹ Mày bị t địt sập cầu sập cống",
    "Súc sinh k trình mà đòi bem anh hả th đú:))))",
    "bem với cha phải banh đầu óc chó ra đáp lại nghe chưa",
    "Cay cú anh trong lòng mà không làm đc gì",
    "Cái con không có địa vị bằng 1 cn súc vật nữa",
    "Cha mày gõ cho mày nguyên 1 tràn lan đại hải",
    "Gõ cho mày tá hỏa tâm tinh",
    "Gõ để mày siêu thoát quá thế giới bên kia",
    "Mày bị cha hành cho cay cú mà",
    "Gõ sồn máu lồn mày lên",
    "Não bị cha mày cho tàn phế r à",
    "Bị anh cho ngậm đống hành trong mõm r",
    "Lgbt bày binh bố trận dồn cha hả",
    "Cha mày bón cứt dô mõm m nè",
    "Cha mày bón cứt dô mõm m nè",
    "Nhìn mặt m là bt không ổn r",
    "Cn tinh tinh bị cha đọa đày",
    "Bị cha mày đọa đày xuống diêm la địa phủ",
    "Để đầu thai chuyển kiếp thành súc vật",
    "Rồi lun cn ôn thú bị anh sỉ nhục mẹ r",
    "Cay quá nên uống nc đái chó cho đỡ cay đi em",
    "Bị cha cho tha hóa thành cchó ngu dốt",
    "M lấy xác chuột nhét vô lồn mẹ m à",
    "Mày bần hèn vậy à thằng óc cứt",
    "M lấy xác chuột nhét vô lồn mẹ m à",
    "Tk não vô sinh ngu ngục quỳ lạy bố đê",
    "Tk não vô sinh ngu ngục quỳ lạy bố đê kkk",
    "sợ bố mà xạo lồn à con",
    "nổ trứng dái chưa em",
    "M có ổn k đó :)))",
    "Tổ cha m con nghiệt súc",
    "Tk cha m học bổ túc hay gì mà m ngu thế ku",
    "Ngu hết phần thiên hạ ngu chuyện lạ dân gian ngu vượt ngàn con chó à :)))",
    "Ăn hại lên phím phản kháng à :)))",
    "Vùng vẫy trước cái chết à :)))",
    "Nổi kh đó tk ngu :)))",
    "T thấy m hơi bất ổn r đấy :)))",
    "Chọc tí đã cay r ak :)))",
    "Người gì nóng tính thế k bt :)))",
    "Nóng tính thế đã xiên cha mẹ phát nào chưa :)))",
    "Chưa thì xiên tk cha m đi để mẹ m cho t :)))",
    "Lô lô cái tk ngu học :)))",
    "Lương 3 cọc lên mạng sĩ gì v em :)))",
    "Bật đt lên là thấy m tru tréo y như là con cầy :)))",
    "Quá khứ hiện tại tương lai của m sẽ xuống cầu y như cái tk cha m :)))",
    "Nhảm nhảm t đá vào họng m nhen :)))",
    "Phảng kháng gì yếu vậy tk ăn hại :)))",
    "M làm được việc k thế :)))",
    "M cay lắm r à :)))",
    "Cay r mày làm gì được t không :)))",
    "Ăn vạ tao à :)))",
    "Bớ làng nước ơi tk ngu nó ăn vạ t nè :)))",
    "Tao lại cho m ăn vả bh chứ đòi ăn vạ :)))",
    "Mxh rách còn thua thì m định làm ăn gì cho đời :)))",
    "Chết mẹ đi cho đỡ chật đất em ak :)))",
    "Bất lực lắm r à tk ku :)))",
    "Kệ con mẹ m bố cứ dập ấy :)))",
    "T dập m như t dập mẹ m tối qua mà :)))",
    "T chọc có tí sao nổ dái r thế :)))",
    "Có phải họ gọi tao là bố mày nên mày suốt ngày tìm đến tao :)))",
    "Bố nói kh nghe à bướng hả con zai :)))",
    "Tk mất dạy chửi bố nó kìa ae :)))",
    "Bố nó nó còn chửi chắc bạn bè nó xiên luôn r :)))",
    "Bảo sao tự kỉ miết :)))",
    "Bất mãn thì kể đi không tí lại ỉa mẹ ra quần :)))",
    "Trình quèn thể hiện văn thơ à :)))",
    "Văn thì cũ vần thì ngu m định cầm đến để tấu hài à :)))",
    "Tao thả vài câu là lũ ngu chạy hết vì t là bố của cái lũ chúng m mà :)))",
    "T đâu có mua vé xem phim hài t mua vé xem xiếc khỉ mà :)))",
    "M bonus cho t thêm màn trình diễn hài l của m à :)))",
    "Vl khỉ thành tinh à :)))",
    "123 lalala 456 địt cha nhà m :)))",
    "Con chó con mèo con ghẹ nhưng tao chỉ thích con mẹ m thôi :)))",
    "Cái đù mẹ tk ngu tung skill gì đây :)))",
    "T đạp cho mấy phát hết mẹ skill bh :)))",
    "Ngày anh sinh ra là ngày mày có thêm 1 người bố à :)))",
    "Cố làm anh cay à :)))",
    "Oke làm đi để anh xem trình quèn m làm được gì không :)))",
    "Anh không cay là con mẹ m nằm trên đường ray nhen :)))",
    "Anh chửi bừa mấy câu bằng mẹ nó kiến thức cả đời m rồi à :)))",
    "Không phản bác được à :)))",
    "Có phản vào cái lồn mẹ m :)))",
    "Liệu m có ổn không khi ngôn từ anh như cơn bão cuốn trôi cmm đi :)))",
    "Không sủa nổi cút ra chỗ khác chơi :)))",
    "M chĩa mõm về t vì chó sắp ra đi thì mõm nó chĩa về chủ à :)))",
    "Cũng trung thành mỗi tội không biết sủa :)))",
    "Bọn trộm chó nhìn mặt m còn khinh :)))",
    "Phế vật sủa không nổi à :)))",
    "Phế hơn tk cha già m nữa :)))",
    "Câm lặng rồi à :)))",
    "Câm bố vẫn chửi đấy :)))",
    "Làm cc gì dc bố kh ấy :)))",
    "Coi tk ngu cay t kìa ae :)))",
    "Sao bão không cuốn trôi cmm đi cho không khí trong lành nhỉ :)))",
    "nay làm việc thiện dọn rác nhé :)))",
    "ngoan nằm im anh quét đi nào :)))",
    "cứ ngẫm từ từ mấy câu của anh đi :)))",
    "nhai luôn cũng dc nhé :)))",
    "nhà anh nuôi mỗi m thôi nhai cho hết đi đừng để lại :)))",
    "anh m lười dọn lắm :)))",
    "sao :)))",
    "thua không phục à :)))",
    "cáu anh lắm à :)))",
    "tức anh lắm à :)))",
    "kệ con mẹ m chứ :)))",
    "m lmj đủ tầm ảnh hưởng :)))",
    "cn choa ei=))=))=))=))",
    "m chay anh cmnr=))=))=))=))=))",
    "m yeu ot z tk ngu=))=))=))=))=))",
    "m cham vl e=))=))=))",
    "slow lun e=))=))=))=))",
    "yeu z cn dix=))=))=))=))",
    "tk 3de=))=))=))=))=))",
    "tk dix lgbt=))=))=))=))",
    "cn choa ngu=))=))=))=))=))",
    "deo co canh lun e=))=))=))=))",
    "m cham vl e=))=))=))=))",
    "m yeu v=))=))=))=))=))=))",
    "yeu ro=))=))=))=))=))=))",
    "bia a=))=))=))=))",
    "tk dix=))=))=))=))",
    "mau k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "cham a=))=))=))=))=))=))",
    "tk ngu =))=))=))=))=))",
    "mau ti de=))=))=))=))",
    "yeu ot vcl=))=))=))=))",
    "cmm dot tu kia=))=))=))",
    "lien tuc de=))=))=))=))=))",
    "alo may cn cho nu=)) =)) =))",
    "cmm =))=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk ngu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "alo alo=))=))=))=))",
    "cn tó ei=))=))=))",
    "mau ti e=))=))=))=))",
    "mau de=))=))=))=))",
    "yeu ot v=))=))=))",
    "tk ccho ei=))=))=))",
    "m tru noi k ay=))=))=))=))",
    "tk 3de=))=))=))=))",
    "cn ga ei=))=))=))=))",
    "m ga vl lun e=))=))=))=))",
    "alo alo=))=))=))",
    "sao ay nhi=))=))=))=))",
    "anh lai win a=))=))=))=))",
    "uoc loser ma=))=))=))=))",
    "tk ngu ei=))=))=))=))",
    "slow k ay=))=))=))",
    "cn cho =))=))=))",
    "speed lun e=))=))=))",
    "toi die k e=))=))=))",
    "mau me m di=))=))=))=))",
    "tk cho ngu=))=))=))=))=))",
    "m ot bo ro=))=))=))=))",
    "m bia a=))=))=))=))=))",
    "con gi khac k=))=))=))=))",
    "tk ga ei=))=))=))",
    "mau k e=))=))=))=))=))",
    "anh win cmnr=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk ngu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau me m di=))=))=))=))",
    "tk cho ngu=))=))=))=))=))",
    "a đấng hot war mà=))=))=))=))",
    "cmm chối à=))=))=))=))",
    "a hw mẹ r=))=))=))=))",
    "con gi dau ma noi =))=))=))=))",
    "a treo co me m ma=))=))=))=))",
    "a win ma=))=))=))=))",
    "m bia a=))=))=))=))",
    "tk ngu ri=))=))=))=))=))",
    "m ngu v =))=))=))=))",
    "ngu ro lun e=))=))=))=))=))",
    "bia a e=))=))=))=))",
    "le de alo =))=))=))=))",
    "s do =))=))=))=))=))",
    "m sao =))=))=))=))",
    " m chạy a mà=))=))=))=))",
    "m bịa à=))=))=))=))",
    " tk nu=))=))=))=))=))",
    "cmm =))=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk ngu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "alo alo=))=))=))=))",
    "cn tó ei=))=))=))",
    "mau ti e=))=))=))=))",
    "mau de=))=))=))=))",
    "yeu ot v=))=))=))",
    "tk ccho ei=))=))=))",
    "m tru noi k ay=))=))=))=))",
    "tk 3de=))=))=))=))",
    "cn ga ei=))=))=))=))",
    "m ga vl lun e=))=))=))=))",
    "alo alo=))=))=))",
    "sao ay nhi=))=))=))=))",
    "anh lai win a=))=))=))=))",
    "uoc loser ma=))=))=))=))",
    "tk ngu ei=))=))=))=))",
    "slow k ay=))=))=))",
    "cn cho =))=))=))",
    "speed lun e=))=))=))",
    "toi die k e=))=))=))",
    "tru ma=))=))=))",
    "tru ne tk ngu=))=))=))=))=))",
    "m tru k noi a=))=))=))=))=))",
    "m yeu v a=))=))=))=))",
    "tk ga ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))=))",
    "yeu z=))=))=))=))=))",
    "cn choa ngu=))=))=))=))=))",
    "sao do=))=))=))=))=))=))",
    "chay bo a=))=))=))=))=))",
    "bo manh vl=))=))=))=))",
    "bo dl ba ro=))=))=))=))",
    "m chay a ma=))=))=))",
    "anh hot war ma e=))=))=))=))=))",
    "anh hot trụ cmnr=))=))=))=))=))",
    "m lam lai a k =))=))=))=))",
    "lam lai anh deo dau ma=))=))=))=))",
    "chay anh ro r=))=))=))=))",
    "con gi khac k=))=))=))=))=))",
    "m bia a=))=))=))=))",
    "tk ngu ei=))=))=))=))",
    "cam m bia ma=))=))=))=))",
    "bia cn gia m dot tu e=))=))=))=))=))",
    "lofi chill k=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "ê=)) =))=))=))=))",
    "m chay anh cmnr=))=))=))=))=))",
    "m yeu ot z tk ngu=))=))=))=))=))",
    "m cham vl e=))=))=))",
    "slow lun e=))=))=))=))",
    "yeu z cn dix=))=))=))=))",
    "tk 3de=))=))=))=))=))",
    "tk dix lgbt=))=))=))=))",
    "cn choa ngu=))=))=))=))=))",
    "deo co canh lun e=))=))=))=))",
    "m cham vl e=))=))=))=))",
    "m yeu v=))=))=))=))=))=))",
    "yeu ro=))=))=))=))=))=))",
    "bia a=))=))=))=))",
    "tk dix=))=))=))=))",
    "mau k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "cham a=))=))=))=))=))=))",
    "tk ngu =))=))=))=))=))",
    "mau ti de=))=))=))=))",
    "yeu ot vcl=))=))=))=))",
    "cmm dot tu kia=))=))=))",
    "lien tuc de=))=))=))=))=))",
    "a cam m ngung ma=))=))=))=))",
    "m ngung la cn gia m die lun e=))=))=))=))=))",
    "m tin anh cam ak47 ban chet me m k=))=))=))=))=))=))",
    "tk ngu bi a dl six nhuc cay vcl lun ma=))=))=))=))=))=))=))",
    "cn gia m lam cave ma bi chê a tk ngu=))=))=))=))=))",
    "cn gia m lam cave để nuôi m à=))=))=))=))=))=))=))=))",
    "m nhai a cn di =))=))=))=))=))",
    "mau ko em=))=))=))=))",
    "tin a cam cay dinh ba dam chet me m k=))=))=))=))=))=))",
    "tk ngu sua lien thanh nhu mp40 anh xem nao=))=))=))=))=))=))",
    "mau e=))=))=))=))=))=))=))",
    "mau de=))=))=))=))=))",
    "tk ga=))=))=))=))=))",
    "tk di=))=))=))=))=))",
    "mau k=))=))=))=))=))=))",
    "mau e=))=))=))=))=))",
    "sp e=))=))=))=))=))",
    "speed mau=))=))=))=))=))",
    "cham chap a=))=))=))",
    "tk phe pham=))=))=))=))",
    "m phe vc e=))=))=))",
    "m tru toi chet k e=))=))=))",
    "le lun e=))=))=))=))",
    "m yeu vc=))=))=))",
    "cn ga ei=))=))=))=))",
    "mau k ay =))=))=))=))",
    "le lun e=))=))=))=))=))",
    "chill k e=))=))=))=))",
    "sua de e=))=))=))=))",
    "mau de alo alo=))=))=))=)",
    "con chó ngu =)))",
    "sua mau =)))",
    "speed em ei =)))",
    "slow à em =)))",
    "m gà mà =)))",
    "sủa kia =)))",
    "chậm v ơ =)))",
    "câm hả em =)))",
    "cho m câm deo =)))",
    "con chó chết =)))",
    "thứ chó gà =)))",
    "yếu v ơ =)))",
    "con đĩ ei =)))",
    "nhanh cho t =)))",
    "dit me m chậm =)))",
    "chậm vc =)))",
    "sao sao =)))",
    "lẹ tay em =)))",
    "run à em =)))",
    "soạn à =)))",
    "deo cho soạn =)))",
    "con chó đĩ =)))",
    "m sao =)))",
    "sao =)))",
    "tức bố =)))",
    "con đĩ mẹ m =)))",
    "yếu mà xạo =)))",
    "địt mẹ m =)))",
    "chậm rõ =)))",
    "hăng mau =)))",
    "chó chậm =)))",
    "chậm như rùa =)))",
    "sồn mau =)))",
    "hăng lẹ ơ =)))",
    "con chó lồn =)))",
    "chó chết =)))",
    "câm à em =)))",
    "m cám mẹ r =)))",
    "đúng k con chó =)))",
    "chó gà kia =)))",
    "m gà =)))",
    "sao lại t =)))",
    "chat mau =)))",
    "con đĩ ei =)))",
    "con chó ei =)))",
    "ko lại t à =)))",
    "m gà vc =)))",
    "chó đực =)))",
    "sao lại t =)))",
    "lêu lêu =)))",
    "th cac bde =)))",
    "ko lại t hả =)))",
    "con đĩ =)))",
    "m ngu ma =)))",
    "gà vcl =)))",
    "đòi win t =)))",
    "yếu như chó =)))",
    "sao win =)))",
    "mẹ m ó =)))",
    "thứ gà =)))",
    "m sao em =)))",
    "m sao =)))",
    "sao nà =)))",
    "gà v =)))",
    "ớt r á =)))",
    "cay =)))",
    "cay kia =)))",
    "liu liu =)))",
    "bại t =)))",
    "hăng lẹ =)))",
    "ngáo r =)))",
    "chua gi câm =)))",
    "t cho câm đâu =)))",
    "tức teo =)))",
    "tức ko lmj dc =)))",
    "cay ngay =)))",
    "con chó =)))",
    "cố lên m =)))",
    "ớt bố ko =)))",
    "tức chết =)))",
    "haha =)))",
    "cuoi die =)))",
    "con đĩ mẹ m =)))",
    "mau mau =)))",
    "chó ei =)))",
    "mau lên =)))",
    "chậm the =)))",
    "me m chet =)))",
    "chó chậm =)))",
    "chậm rõ ơ =)))",
    "chậm vc =)))",
    "k nhanh a =)))",
    "m soan le =)))",
    "con cho nay ga =)))",
    "ga nhu cho =)))",
    "cung bay dat =)))",
    "đú đú =)))",
    "dit me m do =)))",
    "thứ lồn ei =)))",
    "gà v em =)))",
    "có sức ko =)))",
    "soạn mau =)))",
    "mau lơn =)))",
    "con chó cứt =)))",
    "sủa ko =)))",
    "di me m =)))",
    "chó ga =)))",
    "ga kia =)))",
    "mau lên kia =)))",
    "hang mau em ei =)))",
    "chậm rõ =)))",
    "m sao =)))",
    "con chó đuối =)))",
    "chet r à em =)))",
    "ga kia =)))",
    "m xạo =)))",
    "bại t =)))",
    "mà hăng v =)))",
    "leu leu =)))",
    "con cho ng u =)))",
    "câm a =)))",
    "câm bố win =)))",
    "vậy ma =)))",
    "sao ko =)))",
    "cố lên =)))",
    "cbi thua kia =)))",
    "yeu kia =)))",
    "dmm a =)))",
    "con cún nay =)))",
    "hài à =)))",
    "di me m =)))",
    "thứ chó =)))",
    "mau =)))",
    "kiki ei =)))",
    "con cho ei =)))",
    "con gà ei =)))",
    "mau lên =)))",
    "sồn lên =)))",
    "hăng mau =)))",
    "con chó chet =)))",
    "di me m =)))",
    "chậm rồi =)))",
    "chậm ro =)))",
    "khoc r a =)))",
    "chua gi meu =)))",
    "m ớn chua =)))",
    "t thay r =)))",
    "sợ ah ro =)))",
    "ha ha =)))",
    "yeu ro =)))",
    "mà xạo xạo =)))",
    "thứ chó =)))",
    "sua le le =)))",
    "ko t giet =)))",
    "alo =)))",
    "kk =)))",
    "m gà chet =)))",
    "sua sao em =)))",
    "m sua =)))",
    "sua t coi =)))",
    "con choá cái =)))",
    "th l dan toc =)))",
    "m sao =)))",
    "sao =)))",
    "k sua a =)))",
    "sua mau =)))",
    "me m a =)))",
    "th ngu =)))",
    "mau len =)))",
    "con di =)))",
    "sua len ơ =)))",
    "con cho nay =)))",
    "m chet r a =)))",
    "hang len =)))",
    "mau hang =)))",
    "k hăng a =)))",
    "so ah ro =)))",
    "con di ei =)))",
    "m sao =)))",
    "con chó ngu =)))",
    "con dốt ei =)))",
    "dốt kia em =)))",
    "sao kia =)))",
    "con chó cứt =)))",
    "mau lên =)))",
    "mau em =)))",
    "gà rõ à =)))",
    "hay nha =)))",
    "m gà =)))",
    "sua lien tuc ei =)))",
    "k nhanh a =)))",
    "chạy á =)))",
    "cho deo dau =)))",
    "con di me m =)))",
    "tới chết mau =)))",
    "leu leu =)))",
    "sợ ah kia =)))",
    "hài vc =)))",
    "con choá này =)))",
    "sua mau =)))",
    "con di me m =)))",
    "sua len =)))",
    "hang kia =)))",
    "con chó cay =)))",
    "soạn mau =)))",
    "ghê a =)))",
    "ah manh =)))",
    "m yếu =)))",
    "th loz oi =)))",
    "yếu kia =)))",
    "sao ne =)))",
    "con di nay =)))",
    "mau lên =)))",
    "me m =)))",
    "châm a =)))",
    "cay ah iia =)))",
    "sợ a êm  =)))",
    "con choá nay =)))",
    "nó gà =)))",
    "mà xạo kia =)))",
    "th ng u ei =)))",
    "chậm chậm mà xại =)))",
    "sua tiep con di =)))",
    "con chó yeu =)))",
    "đáy xh =)))",
    "mà xạo thoi =)))",
    "huhu =)))",
    "so mày bại =)))",
    "bại ah kia =)))",
    "con chó cứt =)))",
    "bại ah dkd =)))",
    "dit me m =)))",
    "dit luon =)))",
    "kay ak em =)))",
    "sua len =)))",
    "con cho ga =)))",
    "ga kia =)))",
    "ga ro mà =)))",
    "choi ko =)))",
    "chối kệ m =)))",
    "m van ngu =)))",
    "haha =)))",
    "ngu kia =)))",
    "con chó cứt =)))",
    "ngu ma chối =)))",
    "la t dmm =)))",
    "nha con chó =)))",
    "cái con chó cái =)))",
    "m kay me r =)))",
    "kay bố r =)))",
    "lêu lêu =)))",
    "m phe v tk ngu=))=))=))=))=))",
    "cmmm B-)=))=))=))",
    "le k e=))=))=))=))",
    "đ ai treo lun =))=))=))=))=))",
    "m treo a=))=))=))=))=)",
    "m treo me r=))=))=))=))",
    "bia a=))=))=))=))",
    "man k =))=))=))=))",
    "man ne =))=))=))=))",
    "tk ngu ei=))=))=))=))",
    "cmm =))=))=))=))",
    "11 man box k =))=))=))=))=))",
    "lo lo tk ngu=))=))=))O:-)",
    "m yeu ot a=))O:-)=))=))=))=))",
    "yeu ro ma=))=))=))=))=))",
    "xao a =))=))=))=))=))",
    "tk ga ei=))=))=))=))",
    "mau k e=))=))=))=))=))",
    "le nun e=))=))=))=))",
    "ngu a=))=))=))=))",
    "a hot trụ cmnr=))=))=))=))",
    "m lam lai a deo dau=))=))=))=))",
    "cay a =))=))=))=))",
    "cay bo ro=))=))=))=))",
    "bia a tk di=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de e=))=))=))=))",
    "le lun e ei=))=))=))=)",
    "mau ti di=))=))=))",
    "m phe v=))=))=))=))",
    "ot bo ro=))=))=))=))",
    "con gi choi k tk ngu=))=))=))=))",
    "cmm =))=))=))=))",
    "le e=))=))=))=))",
    "mau de=))=))=))=))",
    "nhanh e=))=))=))=))=))",
    "mau e=))=))=))=))",
    "cham a=))=))=))",
    "cham ro=))=))=))=))",
    "bia a=))=))=))=))=))",
    "tk ngu =))=))=))=))",
    "m culi a ma=))=))=))=))=))",
    "ei tk lgbt=))=))=))=))=))",
    "m k dam phan dl a=))=))=))=))=))",
    "m chay a ro ma=))=))=))=))",
    "con gi de choi k=))=))=))=))",
    "k con a=))=))=))=))",
    "the a victory nhe=))=))=))=))",
    "bo uoc loser ma=))=))=))=))=))",
    "uoc nun ay=))=))=))=))",
    "tk choa ei=))=))=))",
    "mau ko cn di=))=))=))=))",
    "cn me m =))=))=))=))",
    "m phe v a=))=))=))=))",
    "tk sv=))=))=))",
    "cn gia m 4 chan a=))=))=))=))=))",
    "4 chan ro =))=))=))",
    "bia ak=))=))=))=))",
    "m cham chap v=))=))=))=))",
    "ê=))  sua le di e=))=))=))=))",
    "speed 0,1s di tk ngu=))=))=))=))",
    "le mau =))=))=))=)",
    "chil chil cx win chan v=))=))=))=))",
    "m ga vcl =))=))=))=))",
    "ga ro =))=))=))=))",
    "bia a=))=))=))=))",
    "tk ngu=))=))=))",
    "mau ko e=))=))=))=))",
    "le mau=))=))=))=))",
    "le mài=)))",
    "ê ê con óc cứt=)))",
    "ah đụ chết cn đĩ mẹ mày mà=)))",    
    "Tao địt mẹ Bạn đến mấy lần rồi con",
    "Tinh trùng khuyết tật",
    "Hồi đó ba Bạn Không dùng bao nên lòi ra thằng mặt cặc như Bạn đó",
    "Con mẹ Bạn",
    "Thằng lồn óc chó",
    "Thứ súc vật",
    "Tao là bố của mẹ Bạn",
    "Chửi chết con mẹ Bạn luôn",
    "Có giỏi thì bơi ra chửi tay đôi đi thằng lồn",
    "Bạn nghĩ gì mà động vào Đại Ca tao",
    "Loại rác rưỡi như Bạn thì Không có tuổi",
    "Bạn có phải con chó Không?",
    "Người Không thể ngu vậy được",
    "Cút con mẹ Bạn đi...",
    "Thứ lồn, đỉ mẹ Bạn",
    "Bạn động nhầm người rồi con chó ạ",
    "Bố Bạn chấp, thứ súc sinh đội lớp thú",
    "Chửi chết mẹ Bạn luôn",
    "Lần sau gặp Đại Ca tao thì né xa ra, địt mẹ Bạn",
    "lồn mẹ mày ăn hại=))",
    "cn đĩ ngu ei=))",
    "mày óc chó rõ mà=)))",
    "cn đỉ mồ cồi cay ah r phải hơm",
    "ớt ah rõ nun mà",
    "ai cho mày slow v á",
    "cn ngu 0 cha 0 mẹ lên mxh đú ak=)))",
    "cha mẹ m bị ah đập tơi bời mà",
    "cn gái mẹ m bị ah dẫm đạp mà=)))",
    "cn mụ già đó bị ah sút tung lồn tử vong nun mà ccho ngu bại não=)))",
    "tk đĩ cha mày nó óc chó quá bị ah đập ngay trc mắt m mà=))))",
    "m bất lực khóc khi thấy ah đập cn đỉ cha m mà",
    "tao đụ rách lồn cn đỉ mẹ mày nun mà=))))",
    "cn mẹ m là đỉ đứng đường bị mấy ccho hiếp dâm liên tục 7749 ngày lun mà=)))",
    "cô đĩ bất lực r phải hơm=)))",
    "mày lmj đc ah nè ccho ngu ei=))))",
    "m mếu r phải hơm cn chó ngu ei=))",
    "đéo mẹ mày tếu à=))))",
    "cn chó nghịch tử tự tay giết chính cn đỉ mẹ nó vì k đc cn gái mẹ nó đy cho đụ=))))))",
    "mày hận ah r đúng k cn đỉ ngu=))) =))) =)))",
    "t sỉ nhục cn mẹ mày cơ=)))",
    "tk cha mày bị ah tra tấn 3 ngày 3 đêm nun mà=))",
    "cn đỉ nó cay cay ah r kìa=))))",
    "ah cho phép m khóc chx đó=)))",
    "t cho m mếu à=)) =)))",
    "cái sự cay cú của m đạt x1000 r phải hơm=)))",
    "cn đĩ slow ác v =)))",
    "m cay ah rõ nun mà kkk=))",
    "óc chó sồn mau đê em ei=))))",
    "mày hăng lên ah xem đê=))",
    "lên ẳng ẳng như cách m ảo ửa đê=)) =)))",
    "cái cn đỉ mẹ mày bất lực r è=))",
    "cay ah mà đâu có lmj đc ah",
    "cn đỉ mồ côi mất cha vì bị ah giết cha",
    "mất mẹ vì cn gái mẹ nó bỏ nó theo ah xg bị ah tra tấn",
    "cn gái mẹ ngoài rộng mà còn thâm nx=)))",
    "tk cha m lm quần quật để cn chó như m lên mxh đú ửa =)))",
    "cn chó cay đập điện thoại xg bị ôg già đánh=)))",
    "sau khi bị đánh cay rút dao tự tay giết cha nó=))",
    "cn chó ngu sau khi bị ah chửi nó kiểu",
    "cn đỉ ei m lên sủa lofi ah xem đê",
    "ai cho m ngồi trg góc tối khóc mà k care ah=))",
    "cn đỉ mếu khóc vì k đc đụ gái mẹ nó=)))",
    "miệng thì chối nhưng não thì nghĩ cách loạn luân =)))",
    "nhìn cu e bất lực mà ah mắc cười",
    "mấy cái ngôn lỏ của m đủ lm ah cay ak",
    "cố làm bố hận m đê",
    "lm ah ớt m đi ccho ngu ei",
    "nghĩ bố cay m ak=)))",
    "não thì tự nhận mik win nhưng thực tế là bại t mà=))",
    "nó cay cay tui r kìa",
    "cn đĩ bại não cố tí ah xem",
    "cn chó vô dụng phế nhất mxh mang tên m mak",
    "đỉ ngu cố gắng win nhưng đâu có đc",
    "cố tí đi sắp thua t r kìa",
    "lose cố gắng tí đê",
    "0 trình đòi pem ai=))",
    "lm trò hề cho thiên hạ xem ak=)))",
    "cn đĩ ngu lên đê=))",
    "ah cho phép m câm ak",
    "ai cho m nín họng chó v",
    "nhìn ah gõ m mà học hỏi",
    "cố gắng học lỏm ah để mai sau cầm ngôn ah pem ah",
    "hôm nay m gặp ah là chết cái cn gái mẹ m r =)))",
    "ah cầm cái bồ cào cái nát cái lồn mẹ mày mà=))",
    "thấy ah chửi m chỉ bt câm nín thôi ak=))",
    "chả lmj đc ah ak=}}",
    "ah khuyên tht m nên chết đi=))",
    "sống làm cái đéo giề =))",
    "cn đỉ mẹ mày nun=))",
    "m có căn để pem ah hơm=))",
    "cái lồn mẹ mày nun nè=))",
    "cái cn chó ngu eiiii=)))",
    "ah cho m sủa sao m ko sủa đê",
    "nãy hăng lắm mà=}}",
    "cn đỉ ăn bánh mì quanh năm suốt tháng",
    "ăn lun cả tinh trùng của cn đỉ cha nó",
    "cn đỉ lgbt bày bình chơi ah mà ai ngờ lép vế",
    "cn mẹ mày là đĩ cơ=)))",
    "m phế đến nổi chửi 1 đứa k bt ửa r noti ngầu ngầu=)))",
    "hôm nay gặp ah bại trận trc ah lun mà=)))",
    "cn chó oanh liệt lắm h sao im thin thít r nè",
    "cái tk đĩ ăn hại=)))",
    "ah cầm đinh ba xiên chết cha m cơ=))",
    "ah đụ rách lồn mẹ mày mà",
    "m rung sợ cha rõ mà",
    "ah sút tung lồn mẹ m =))",
    "ah treo cổ cha mày mà",
    "cn đĩ ngu lại bố ko v =))",
    "nhìn m đuối đuối r kìa cn ngu =))",
    "phèn lồn mà tưởng mình bá hả =))",
    "làm đc bố thua m ko v cn đĩ =))",
    "mày xàm xàm jv cn đĩ =))",
    "cái con đĩ mẹ mày ngôn phèn lồn mà m tưởng dame cao hả con đĩ =))",
    "cái lồn mẹ mày làm lại tao v cn chó đú =))",
    "ngày m gặp anh là ngày ah đập chết cn gái mẹ mày ấy =))",
    "cái tk lồn mặt cặc sida mà tưởng mình hay =))",
    "m câm 1 cái là ah triệu hồi thiên lôi đánh chết cn đĩ mẹ mày ấy =))",
    "ah cho m sủa lofi trog 5p đấy cn đĩ ơi =))",
    "ngôn lồn phèn mà tưởng ngầu =))",
    "m tưởng m hw hả cn đĩ lồn ơi =))",
    "trình m đáy xã hội còn t trên đọt cây cn đĩ mẹ mày r =))",
    "ngu lồn sĩ sĩ t đánh chết cn mẹ mày =))",
    "cn lồn mếu r hả e ơi =))",
    "t ước cay đc bởi cái ngôn lồn óc cặc sida đần độn phèn lồn của m ấy =))",
    "m cố làm ah cay đi cn đĩ ơi =))",
    "cái cn lồn yếu đuối mà sĩ à e =))",
    "đụ đĩ mẹ mày phế vật à e =))",
    "t cầm đinh ba xiên chết cha m mà =))",
    "t đụ rách cái lồn mẹ mày mà =))",
    "bố réo tổ tông nhà m còn đc =))",
    "cn chó loạn luân vs cn gái mẹ nó rõ mà=))",
    "t tung skill lm cn gái mẹ m die lun cơ =))",
    "tk đĩ culi ăn hại chửi k sát thương mà =))",
    "m muốn win cha m đâu có đc =))",
    "cn đĩ mẹ mày làm lại ah ko tk ăn hại =))",
    "cn chó âm binh đầu đinh =))",
    "cn chó 0 cha 0 mẹ oai ak=))",
    "văn thơ ah bay trog gió dã vô lồn mẹ mày =))",
    "đĩ ngu idea hạn hẹp =))",
    "cái lồn mẹ mày bị ah đụ nát mà cn đĩ lồn =))",
    "yếu mà sĩ sĩ à e =))",
    "m cố trụ vs ah nha cn đĩ ơi =))",
    "m mà rớt là cn mẹ mày chết =))",
    "m cố gắng nha cn chó mặt cặc =))",
    "rớt ah 1 cái là đụ má cn đĩ mẹ mày die liền á =))",
    "t cầm ak47 sấy nát cái gia đình lồn ăn hại của m =))",
    "tk lồn ơi m lên sĩ lẹ cho anh =))",
    "m sợ bố phải ko cn chó =))",
    "ngữ m vạn kiếp vẫn chưa win đc ah cơ =))",
    "cn chó ăn hại tự xưng hw bị ah đánh chết mẹ cơ =))",
    "m làm thân vs t là t vã nát lồn má mày =))",
    "m phản kháng trg vô vọng à =)))",
    "t đá chết cha m mà =))",
    "t thay trời tiêu diệt cn má m =)))",
    "t chửi cha mắng mẹ m mà =))",
    "cn chó ngu cay ah=))",
    "cn đĩ ngu ăn hại=))",
    "m muốn win cha m đâu có đc =))",
    "noti đc cha khó như lên trời ngược lại noti m ez vc =))",
    "cái cn đĩ ngu ngu bắt đầu bí bí r kìa =))",
    "cn đĩ chị m mà cn lồn ơi =))",
    "lồn mẹ mày ăn hại mà đú ửa hả =))",
    "cố gắng tí nha cn đĩ lồn =))",
    "đĩ mẹ mày bày đặt sĩ sĩ hả cn ngu =))",
    "lồn má mày cấm out box nghe chưa cn ăn hại =))",
    "1 khi ah réo là ah réo chết cn mẹ mày thì thôi mà =))",
    "đừng có quỳ xuống cầu xin ah nghe chx =))",
    "ăn hại mà tưởng mình là hw cơ =))",
    "lại phải win cn chó như m =))",
    "chuỗi 1 triệu tiêu diệt cn gái mẹ mày =))",
    "cn lồn nghịch tử tự tay giết cha đánh đuổi mẹ ruột mà chối =))",
    "cn đĩ xạo lồn mà oai =))",
    "cn đĩ mẹ mày xạo lồn hả cn chó =))",
    "cn gái mẹ mày làm lại tao ko v cn đĩ mặt cặc ăn hại =))",
    "đụ đĩ mẹ mày đuối rõ mà e =))",
    "chối cái ah vã cn gái mẹ mày chết =))",
    "lồn ăn hại ơi =))",
    "cn đĩ mẹ mày bị ah réo chết mẹ mà cn đĩ =))",
    "bị ah trụ cho rớt trg bất lực nên cay pk =))",
    "hận bố r phải k cn đĩ ăn hại =))",
    "ngôn ah dame cao chứ ai như cn đĩ ngôn phèn như m v =))",
    "m đừng để ah noti m ez v chứ =))",
    "cái cn đĩ ăn hại lên mxh sĩ =))",
    "đụ cn gái mẹ mày sao đó =))",
    "cái lồn cn gái mẹ mày cay t hả =))",
    "cn gái mẹ mày đứng đường nuôi m ăn học mà =))",
    "cn mẹ mày chết kìa =))",
    "t giết cn gái mẹ mày r vứt xuống sông hồng =))",
    "cn đĩ ngu ngu cay t r à =))",
    "cn lồn sồn như ban đầu cho bố đi ơ =))",
    "cn đĩ mẹ mày =))",
    "phế vật hả cn chó ơi =))",
    "lm bố thua m mau đi cn chó mặt cặc ăn hại =))",
    "cn chó loạn luân vs cn gái mẹ nó rõ mà=))",
    "t sút chết bà già m mà=))",
    "m mồ côi hả cn đĩ mặt cặc =))",
    "đụ đĩ mẹ mày phế kinh à =))",
    "cn lồn ơi lên sĩ tiếp cho ah =))",
    "sồn như ban đầu cho bố đi ơ =))",
    "cn đĩ mẹ mày cay t à =))",
    "đụ cn gái mẹ mày sắp thua bố hả cn đĩ lồn =))",
    "cn gái má mày bị ah đụ nát cái lồn =))",
    "cn đĩ cấm thua t nghe chưa =))",
    "lm đc t thua m ko v e =))",
    "cái cn miên ơi sĩ tiếp cho t =))",
    "m sồn như ban đầu cho t lẹ e =))",
    "cái cn đĩ mẹ mày phế vật à e =))",
    "cn lồn ngu ăn hại ơi =))",
    "đụ đĩ mẹ mày bị giết mà =))",
    "cn đĩ mặt cặc sồn mau cho ah đi cn đĩ ăn hại ơi =))",
    "đụ má mày sĩ sĩ ngu à e =))",
    "sĩ trai hay sĩ gái v mà nhìn đần v e =))",
    "cái cn lồn mồ côi mà giấu t hả =))",
    "đụ má mày mồ cồi mà xạo lồn =))",
    "lồn mẹ mày cn chó ơi hăng mau k =))",
    "đéo cho m chậm nghe chưa =))",
    "sồn lồn mẹ mày lên ah xem đê =))",
    "cn đĩ mặt cặc cay cay t r =))",
    "đụ đĩ mẹ mày tức bố hả =))",
    "cn mặt lồn ăn hại mà còn xạo lồn =))",
    "ngữ lồn m khi nào lm đc t cay v e =))",
    "cn đĩ đầu trâu mặt ngựa tức t r hả =))",
    "cái lồn má mày nhà nghèo xây mộ mẹ m bé v =))",
    "cái cn đĩ bán dâm mang tên cn gái mẹ mày =))",
    "mẹ mày chết ơ =))",
    "cn đĩ mua thuốc giảm cân đi =))",
    "m loạn luân vs mẹ mày mà =))",
    "t chửi cha mắng cái cn gái mẹ mày =))",
    "cái lồn mẹ mày sợ t à =))",
    "cn lồn ơi m bảo t bot tool này nọ là t chửi chết mẹ mày =))",
    "cái con lồn ngu thấy ah tốc độ quá à =))",
    "cái cn đĩ mẹ mày chết =))",
    "cn chó ngu lồn =))",
    "mẹ mày cn chó =))",
    "sợ bố r à cn ngu =))",
    "đĩ mẹ mày ơ =))",
    "cn gái mẹ mày nun =))",
    "cn đĩ mập địch =))",
    "lm lại ah k v =))",
    "cn đĩ ngu ăn hại =))",
    "đụ đĩ mẹ mày tức t à =))",
    "cái cn lồn ơi =))",
    "cn đĩ mẹ mày m ơ =))",
    "t sút tung lồn mẹ mày cơ =))",
    "cn choa ei=))=))=))=))",
    "123=))=))=))=))",
    "m chay anh cmnr=))=))=))=))=))",
    "m yeu ot z tk nfu=))=))=))=))=))",
    "m cham vl e=))=))=))",
    "slow lun e=))=))=))=))",
    "yeu z cn dix=))=))=))=))",
    "tk 3de=))=))=))=))=))",
    "tk dix lgbt=))=))=))=))",
    "cn choa nfu=))=))=))=))=))",
    "deo co canh lun e=))=))=))=))",
    "m cham vl e=))=))=))=))",
    "m yeu v=))=))=))=))=))=))",
    "yeu ro=))=))=))=))=))=))",
    "bia a=))=))=))=))",
    "tk dix=))=))=))=))",
    "mau k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "cham a=))=))=))=))=))=))",
    "tk nfu =))=))=))=))=))",
    "mau ti de=))=))=))=))",
    "yeu ot vcl=))=))=))=))",
    "cmm dot tu kia=))=))=))",
    "lien tuc de=))=))=))=))=))",
    "alo may cn cho nu=)) =)) =))",
    "cmm =))=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk nfu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "alo alo=))=))=))=))",
    "cn tÃ³ ei=))=))=))",
    "mau ti e=))=))=))=))",
    "mau de=))=))=))=))",
    "yeu ot v=))=))=))",
    "tk ccho ei=))=))=))",
    "m tru noi k ay=))=))=))=))",
    "tk 3de=))=))=))=))",
    "cn ga ei=))=))=))=))",
    "m ga vl lun e=))=))=))=))",
    "alo alo=))=))=))",
    "sao ay nhi=))=))=))=))",
    "anh lai win a=))=))=))=))",
    "uoc loser ma=))=))=))=))",
    "tk nfu ei=))=))=))=))",
    "slow k ay=))=))=))",
    "cn cho =))=))=))",
    "speed lun e=))=))=))",
    "toi die k e=))=))=))",
    "mau me m di=))=))=))=))",
    "tk cho nfu=))=))=))=))=))",
    "m ot bo ro=))=))=))=))",
    "m bia a=))=))=))=))=))",
    "con gi khac k=))=))=))=))",
    "tk ga ei=))=))=))",
    "mau k e=))=))=))=))=))",
    "anh win cmnr=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk nfu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau me m di=))=))=))=))",
    "tk cho nfu=))=))=))=))=))",
    "a Ä‘áº¥ng hot war mà=))=))=))=))",
    "cmm chối à=))=))=))=))",
    "a hw mẹ r=))=))=))=))",
    "con gi dau ma noi =))=))=))=))",
    "a treo co me m ma=))=))=))=))",
    "a win ma=))=))=))=))",
    "m bia a=))=))=))=))",
    "tk nfu ri=))=))=))=))=))",
    "m ngu v =))=))=))=))",
    "ngu ro lun e=))=))=))=))=))",
    "bia a e=))=))=))=))",
    "le de alo =))=))=))=))=))",
    "s do =))=))=))=))=))",
    "m sao =))=))=))=))",
    "m chạy a mà=))=))=))=))",
    "m bịa à=))=))=))=))",
    "tk nu=))=))=))=))=))",
    "cmm =))=))=))=))",
    "sua e=))=))=))=))",
    "mau e=))=))=))",
    "mau de=))=))=))",
    "tk ga=))=))=))",
    "m cham a=))=))=))",
    "m cham ro=))=))=))=))",
    "m bia a=))=))=))",
    "tk nfu ei=))=))=))=))",
    "mau k e=))=))=))=))",
    "mau de=))=))=))",
    "alo alo=))=))=))=))=))",
    "cn choa ei=))=))=))=))",
    "mau ti k=))=))=))=))",
    "mau de=))=))=))=))=))",
    "alo alo=))=))=))=))",
    "nó cay t vcl ra r ae=)))",
    "đĩ mẹ nó nữa chứ=)))",
    "s đó tk cẩu ưi=)))",
    "t chat dài như năm tháng cha nó ở tù=)))",
    "đúng tk ngoại tộc=)))",
    "đĩ má nó=)))",
    "sua nhanh memay ko tk ngu=))=))=))",
    "chui bo lien tuc k tk e=))=))",
    "me may siu oc cho dk e=))=))=))",
    "tk lon siu vo dung an cut e=))=))=))",
    "keo treo zalo 10box 10m ko e=))=))",
    "lien tuc 24 vs anh dc k=))=))",
    "siu met moi r dk tk cuk ngu e=))=))=))",
    "tk lon cho siu run ray r dk e=))=))=))",
    "lam anh cay dc ko tk ngu=))=))=))",
    "con bím ngu siu tuc r a=))=))",
    "tk loz silicon chat vs ah dc k=))=))=))",
    "chui bo nhanh nhen ti dei=))=))",
    "keo tien vs bo ti k=))=))",
    "toxic lau dai ti ko tk cuk=))=))",
    "me may siu vo dung r dk e=))=))=))",
    "tk lon ngu loser bo r dk em=))=))=))",
    "tk loz mat me siu cay a=))=))",
    "uc che bo x100 r dk e=))=))=))",
    "chui nhau hang hai ti ko=))=))=))=))",
    "kho khan khi gap anh dung k tk ngu=))=))=))",
    "con me may an hai dk em ei=))=))",
    "me may chet vi benh tat dk=))=))=))",
    "tk loz cuk culi cay bo k=))=))=))",
    "am uc bo lam r dk=))=))",
    "siu cay anh ma dk e=))=))",
    "chui dc anh ko e=))=))=))=))",
    "tk loz cuk cho memay ei=))=))",
    "tk cuk cho siu ngu ei=))=))=))",
    "memay loser bo r dk=))=))=))",
    "chui bo lien tuc dc k ay=))=))",
    "nhanh nhen ti ko e=))=))=))",
    "siu met moi r dk tk ngu=))=))=))",
    "tk cuk loz ngu e=))=))=))",
    "hang hai vs bo ti ko=))=))=))",
    "chat 24h vs anh dc k=))=))",
    "memay len gg search cach wjn a dk=))=))=))",
    "bo may siu manh dk=))=))",
    "hoa khi bash anh ti k=))=))=))",
    "tk bim siu uc che=))=))=))",
    "lam v co giup memay song lai k=))=))",
    "tk loz ngheo nan ei=))=))=))",
    "memay nha la dk tk e=))=))=))",
    "tk nha ngheo cay bo k=))=))=))",
    "chui bo nhanh dc k=))=))",
    "tk loz ngu bi bo chui dk=))=))",
    "siu cay cu bo dk tk e=))=))",
    "tk cha k chet r dk e=))=))",
    "tk cuk cho dit me may=))=))=))",
    "bo may siu manh dk=))=))=))",
    "chat lien tuc 24h vs anh ko=))=))=))",
    "tk cho siu vo dung ei=))=))=))",
    "bo bash chet may dk e=))=))=))",
    "tk loz siu ga chui dc a ko=))=))=))",
    "tk cho bi a chui sml a em=))=))=))",
    "con me may siu uc che r dk e=))=))=))",
    "chui bo lien tuc 1ti nam ko=))=))=))",
    "lam keo 100m vs anh k=))=))=))",
    "chui a nhanh ti ko=))=))=))",
    "tk loz siu an hai dk e=))=))",
    "keo treo zalo 10box vs ah ko=))=))",
    "tk loz indo siu cay",
    "tuc gian lam r dk thang e=))=))=))",
    "chui win bo dc k e=))=))",
    "co gang win a dei=))=))=))",
    "co chui hang dei em=))=))🎮",
    "bo may siu manh dk tk e",
    "tk cac bi bo chui cay k",
    "con me may loser bo dk e",
    "bo manh siu manh dk e",
    "bo may super vippro dk e",
    "tk cho siu ot bo dk=))",
    "thằng bê đê bất lực vì mẹ nó bị đụ tung cái lồn:)))",
    "con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))",
    "làm màu mà bị tao chửi rung cái con cặc:)))",
    "thằng bê đê ảo cặc đòi cân và cái kết:)))",
    "con đĩ mẹ của mày thèm cứt tao dữ lắm:)))",
    "chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))",
    "ai cho mày sủa tao cho mày sủa chưa?",
    "mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á",
    "mẹ đĩ của m dắt m vào sàn à=))",
    "mẹ mày bú cặc t để m được vào sàn mà",
    "đập đá hít cần sa nhiều xong sủa bậy à",
    "mẹ mày bị tao dã vào lồn=)))",
    "địt mẹ mày sướng tê con cặc=)))",
    "mẹ mày bị tao địt rên ư ử=)))",
    "tao địt mẹ mày nát lồn mà=)))",
    "mẹ mày bị tao cưỡng hiếp=)))",
    "sao mày lề mề dị con",
    "mày bệnh nặng lắm à:)))",
    "ko cảm hứng để hăng à :)))",
    "nghèo k có nghi lực à:))",
    "m thèm cứt t mà:))",
    "chối t giết cha má m nè:)))",
    "k lên t tuyệt chủng m nhen cn thú",
    "mày ngưng là con đĩ mẹ mày chết?",
    "Cha mày đụ chó sinh ra mày đk dog :)))",
    "bị tao chọc cay hơn con chó luôn=)))",
    "Mẹ Mày bị t địt sập cầu sập cống",
    "Súc sinh k trình mà đòi bem anh hả th đú:))))",
    "bem với cha phải banh đầu óc chó ra đáp lại nghe chưa",
    "Cay cú anh trong lòng mà không làm đc gì",
    "Cái con không có địa vị bằng 1 cn súc vật nữa",
    "Cha mày gõ cho mày nguyên 1 tràn lan đại hải",
    "Gõ cho mày tá hỏa tâm tinh",
    "Gõ để mày siêu thoát quá thế giới bên kia",
    "Mày bị cha hành cho cay cú mà",
    "Gõ sồn máu lồn mày lên",
    "Não bị cha mày cho tàn phế r à",
    "Bị anh cho ngậm đống hành trong mõm r",
    "Lgbt bày binh bố trận dồn cha hả",
    "Cha mày bón cứt dô mõm m nè",
    "Cha mày bón cứt dô mõm m nè",
    "Nhìn mặt m là bt không ổn r",
    "Cn tinh tinh bị cha đọa đày",
    "Bị cha mày đọa đày xuống diêm la địa phủ",
    "Để đầu thai chuyển kiếp thành súc vật",
    "Rồi lun cn ôn thú bị anh sỉ nhục mẹ r",
    "Cay quá nên uống nc đái chó cho đỡ cay đi em",
    "Bị cha cho tha hóa thành cchó ngu dốt",
    "M lấy xác chuột nhét vô lồn mẹ m à",
    "Mày bần hèn vậy à thằng óc cứt",
    "M lấy xác chuột nhét vô lồn mẹ m à",
    "Tk não vô sinh ngu ngục quỳ lạy bố đê",
    "Tk não vô sinh ngu ngục quỳ lạy bố đê kkk",
    "sợ bố mà xạo lồn à con",
    "nổ trứng dái chưa em",
    "M có ổn k đó :)))",
    "Tổ cha m con nghiệt súc",
    "Tk cha m học bổ túc hay gì mà m ngu thế ku",
    "Ngu hết phần thiên hạ ngu chuyện lạ dân gian ngu vượt ngàn con chó à :)))",
    "Ăn hại lên phím phản kháng à :)))",
    "Vùng vẫy trước cái chết à :)))",
    "Nổi kh đó tk ngu :)))",
    "T thấy m hơi bất ổn r đấy :)))",
    "Chọc tí đã cay r ak :)))",
    "Người gì nóng tính thế k bt :)))",
    "Nóng tính thế đã xiên cha mẹ phát nào chưa :)))",
    "Chưa thì xiên tk cha m đi để mẹ m cho t :)))",
    "Lô lô cái tk ngu học :)))",
    "Lương 3 cọc lên mạng sĩ gì v em :)))",
    "Bật đt lên là thấy m tru tréo y như là con cầy :)))",
    "Quá khứ hiện tại tương lai của m sẽ xuống cầu y như cái tk cha m :)))",
    "Nhảm nhảm t đá vào họng m nhen :)))",
    "Phảng kháng gì yếu vậy tk ăn hại :)))",
    "M làm được việc k thế :)))",
    "M cay lắm r à :)))",
    "Cay r mày làm gì được t không :)))",
    "Ăn vạ tao à :)))",
    "Bớ làng nước ơi tk ngu nó ăn vạ t nè :)))",
    "Tao lại cho m ăn vả bh chứ đòi ăn vạ :)))",
    "Mxh rách còn thua thì m định làm ăn gì cho đời :)))",
    "Chết mẹ đi cho đỡ chật đất em ak :)))",
    "Bất lực lắm r à tk ku :)))",
    "Kệ con mẹ m bố cứ dập ấy :)))",
    "T dập m như t dập mẹ m tối qua mà :)))",
    "T chọc có tí sao nổ dái r thế :)))",
    "Có phải họ gọi tao là bố mày nên mày suốt ngày tìm đến tao :)))",
    "Bố nói kh nghe à bướng hả con zai :)))",
    "Tk mất dạy chửi bố nó kìa ae :)))",
    "Bố nó nó còn chửi chắc bạn bè nó xiên luôn r :)))",
    "Bảo sao tự kỉ miết :)))",
    "Bất mãn thì kể đi không tí lại ỉa mẹ ra quần :)))",
    "Trình quèn thể hiện văn thơ à :)))",
    "Văn thì cũ vần thì ngu m định cầm đến để tấu hài à :)))",
    "Tao thả vài câu là lũ ngu chạy hết vì t là bố của cái lũ chúng m mà :)))",
    "T đâu có mua vé xem phim hài t mua vé xem xiếc khỉ mà :)))",
    "M bonus cho t thêm màn trình diễn hài l của m à :)))",
    "Vl khỉ thành tinh à :)))",
    "123 lalala 456 địt cha nhà m :)))",
    "Con chó con mèo con ghẹ nhưng tao chỉ thích con mẹ m thôi :)))",
    "Cái đù mẹ tk ngu tung skill gì đây :)))",
    "T đạp cho mấy phát hết mẹ skill bh :)))",
    "Ngày anh sinh ra là ngày mày có thêm 1 người bố à :)))",
    "Cố làm anh cay à :)))",
    "Oke làm đi để anh xem trình quèn m làm được gì không :)))",
    "Anh không cay là con mẹ m nằm trên đường ray nhen :)))",
    "Anh chửi bừa mấy câu bằng mẹ nó kiến thức cả đời m rồi à :)))",
    "Không phản bác được à :)))",
    "Có phản vào cái lồn mẹ m :)))",
    "Liệu m có ổn không khi ngôn từ anh như cơn bão cuốn trôi cmm đi :)))",
    "Không sủa nổi cút ra chỗ khác chơi :)))",
    "M chĩa mõm về t vì chó sắp ra đi thì mõm nó chĩa về chủ à :)))",
    "Cũng trung thành mỗi tội không biết sủa :)))",
    "Bọn trộm chó nhìn mặt m còn khinh :)))",
    "Phế vật sủa không nổi à :)))",
    "Phế hơn tk cha già m nữa :)))",
    "Câm lặng rồi à :)))",
    "Câm bố vẫn chửi đấy :)))",
    "Làm cc gì dc bố kh ấy :)))",
    "Coi tk ngu cay t kìa ae :)))",
    "Sao bão không cuốn trôi cmm đi cho không khí trong lành nhỉ :)))",
    "nay làm việc thiện dọn rác nhé :)))",
    "ngoan nằm im anh quét đi nào :)))",
    "cứ ngẫm từ từ mấy câu của anh đi :)))",
    "nhai luôn cũng dc nhé :)))",
    "nhà anh nuôi mỗi m thôi nhai cho hết đi đừng để lại :)))",
    "anh m lười dọn lắm :)))",
    "sao :)))",
    "thua không phục à :)))",
    "cáu anh lắm à :)))",
    "tức anh lắm à :)))",
    "kệ con mẹ m chứ :)))",
    "m lmj đủ tầm ảnh hưởng :)))"
  ];

  scoldUsers.set(userId, true);
  isScoldingActive = true;

  let count = 0;
  const interval = setInterval(async () => {
    if (!isScoldingActive) {
      const genderText = userTarget.genderId === 0 ? "Thằng Oắt Con" : userTarget.genderId === 1 ? "Oắc Con" : "Thằng Oắt Con";
      await api.sendMessage(
        {
          msg: `${genderText} ${userTarget.name}, nể Đại Ca của tao tha Bạn lần này, cảm ơn Đại Ca tao đi!`,
          mentions: [{ pos: genderText.length + 1, uid: userTarget.uid, len: userTarget.name.length }],
        },
        threadId,
        message.type
      );
      scoldUsers.delete(userId);
      clearInterval(interval);
      return;
    }

    if (count >= scoldMessages.length) {
      count = 0;
    }

    const randomMessage = scoldMessages[count];
    await api.sendMessage(
      {
        msg: `${userTarget.name} ${randomMessage}`,
        mentions: [{ pos: 0, uid: userTarget.uid, len: userTarget.name.length }],
      },
      threadId,
      message.type
    );
    count++;
  }, delay);

  const userTarget = await getUserInfoData(api, userId);
  const caption = `Tao chuẩn bị mắng yêu `;
  await api.sendMessage(
    {
      msg: caption + `${userTarget.name}!!`,
      mentions: [{ pos: caption.length, uid: userId, len: userTarget.name.length }],
    },
    threadId,
    message.type
  );
}
